- hosts: webservers
  become: true
  roles:
    - { role: geerlingguy.docker, tags: [setup] }
    - { role: geerlingguy.nginx, tags: [setup] }
    - { role: nginx_config, tags: [setup] }
    - role: geerlingguy.certbot
      tags: [setup]
      vars:
        certbot_auto_renew: true
        certbot_auto_renew_user: root
        certbot_auto_renew_hour: "3"
        certbot_auto_renew_minute: "30"
        certbot_auto_renew_options: "--quiet --deploy-hook 'systemctl reload nginx'"
        certbot_create_method: webroot
        certbot_create_if_missing: True
        certbot_admin_email: "{{ app_user_email }}"
        certbot_certs:
          - name: "{{ app_domain }}"
            webroot: "{{ app_rootdir }}"
            domains:
              - "{{ app_domain }}"
              - "www.{{ app_domain }}"
    - { role: ufw_rules, tags: [setup] }
    - { role: deploy, tags: [deploy] }

  tasks:
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ app_user | default('deploy') }}"
        create_home: true
        shell: /bin/bash
        groups: docker
        append: true
      tags: [setup]




