- name: Remove default Nginx vhost
  ansible.builtin.file:
    path: "{{ nginx_config_default_nginx_vhost_path }}"
    state: absent

- name: Copy proxy_params configuration
  ansible.builtin.template:
    src: "{{ nginx_config_src_proxy_params }}"
    dest: "{{ nginx_config_dest_proxy_params }}"
    owner: "{{ nginx_config_owner }}"
    group: "{{ nginx_config_group }}"
    mode: "{{ nginx_config_mode }}"

- name: Copy nginx configuration file remote host
  ansible.builtin.template:
    src: "{{ nginx_config_src_nginx_config_file }}"
    dest: "{{ nginx_config_dest_nginx_config_file }}"
    owner: "{{ nginx_config_owner }}"
    group: "{{ nginx_config_group }}"
    mode: "{{ nginx_config_mode }}"
  notify: Nginx reload