deploy_image_repository: "aleksved/project-devops-deploy"
deploy_image_tag: "latest" 
deploy_image_name: "{{ deploy_image_repository }}:{{ deploy_image_tag }}" 
deploy_container_name: "project-devops-deploy"
deploy_spring_profiles_active: "prod"
deploy_spring_datasource_url: "jdbc:postgresql://rc1a-knp27jjb37mp8r82.mdb.yandexcloud.net:6432/bulletins?targetServerType=master&sslmode=require"
deploy_storage_s3_region: "ru-central1"
deploy_storage_s3_bucket: "prod-users-files"
deploy_storage_s3_endpoint: "https://storage.yandexcloud.net"
